import { eChartType } from '../../../+hub/hub.models';

export enum eInputFormat {
    SingleSeries,
    MultiSeries,
    InverseSeries,
    Xy,
    XyMinMax,
    XyBubble,
    GeoCoordinates
}

export const inputFormats = [
{key: eInputFormat.SingleSeries, allowLabel: true, maxSeries: 1, allowYSeries: false,
    allowMinMax: false, allowBubble: false, inverse: false },
{key: eInputFormat.MultiSeries, allowLabel: true, maxSeries: 10, allowYSeries: false,
    allowMinMax: false, allowBubble: false, inverse: false },
{key: eInputFormat.InverseSeries, allowLabel: true, maxSeries: 10, allowYSeries: false,
    allowMinMax: false, allowBubble: false, inverse: true },
{key: eInputFormat.Xy, allowLabel: false, maxSeries: 1, allowYSeries: true,
    allowMinMax: false, allowBubble: false, inverse: false },
{key: eInputFormat.XyMinMax, allowLabel: false, maxSeries: 1, allowYSeries: true,
    allowMinMax: true, allowBubble: false, inverse: false },
{key: eInputFormat.XyBubble, allowLabel: false, maxSeries: 1, allowYSeries: true,
    allowMinMax: false, allowBubble: true, inverse: false },
]

export const ChartTypes = [
    {
        name: 'Bar Charts',
        charts: [
            {
                key: eChartType.BarVertical, name: 'Vertical Bar Chart',
                inputFormat: eInputFormat.SingleSeries,
                isHorizontal: false,
                allowGradient: true,
                allowLegend: true,
                allowXAxis: true,
                allowYAxis: true,
                allowXScaleMin: false,
                allowXScaleMax: false,
                allowYScaleMin: true,
                allowYScaleMax: true,
                allowLabels: false,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: true,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false
            },
            {
                key: eChartType.BarHorizontal, name: 'Horizontal Bar Chart',
                inputFormat: eInputFormat.SingleSeries,
                isHorizontal: true,
                allowGradient: true,
                allowLegend: true,
                allowXAxis: true,
                allowYAxis: true,
                allowXScaleMin: true,
                allowXScaleMax: true,
                allowYScaleMin: false,
                allowYScaleMax: false,
                allowLabels: false,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: true,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false
            },
            {
                key: eChartType.BarVertical2D, name: 'Vertical Bar Chart (MultiSeries)',
                inputFormat: eInputFormat.MultiSeries,
                isHorizontal: false,
                allowGradient: true,
                allowLegend: true,
                allowXAxis: true,
                allowYAxis: true,
                allowXScaleMin: false,
                allowXScaleMax: false,
                allowYScaleMin: false,
                allowYScaleMax: true,
                allowLabels: false,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: true,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false
            },
            {
                key: eChartType.BarHorizontal2D, name: 'Horizontal Bar Chart (MultiSeries)',
                inputFormat: eInputFormat.MultiSeries,
                isHorizontal: true,
                allowGradient: true,
                allowLegend: true,
                allowXAxis: true,
                allowYAxis: true,
                allowXScaleMin: false,
                allowXScaleMax: true,
                allowYScaleMin: false,
                allowYScaleMax: false,
                allowLabels: false,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: true,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false
            },
            {
                key: eChartType.BarVerticalStacked, name: 'Vertical Stacked Bar Chart',
                inputFormat: eInputFormat.MultiSeries,
                isHorizontal: false,
                allowGradient: true,
                allowLegend: true,
                allowXAxis: true,
                allowYAxis: true,
                allowXScaleMin: false,
                allowXScaleMax: false,
                allowYScaleMin: false,
                allowYScaleMax: true,
                allowLabels: false,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: true,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false
            },
            {
                key: eChartType.BarHorizontalStacked, name: 'Horizontal Stacked Bar Chart',
                inputFormat: eInputFormat.MultiSeries,
                isHorizontal: true,
                allowGradient: true,
                allowLegend: true,
                allowXAxis: true,
                allowYAxis: true,
                allowXScaleMin: false,
                allowXScaleMax: true,
                allowYScaleMin: false,
                allowYScaleMax: false,
                allowLabels: false,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: true,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false
            },
            {
                key: eChartType.BarVerticalNormalized, name: 'Vertical Normalized Bar Chart',
                inputFormat: eInputFormat.MultiSeries,
                isHorizontal: false,
                allowGradient: true,
                allowLegend: true,
                allowXAxis: true,
                allowYAxis: true,
                allowXScaleMin: false,
                allowXScaleMax: false,
                allowYScaleMin: false,
                allowYScaleMax: false,
                allowLabels: false,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: true,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false
            },
            {
                key: eChartType.BarHorizontalNormalized, name: 'Horizontal Normalized Bar Chart',
                inputFormat: eInputFormat.MultiSeries,
                isHorizontal: true,
                allowGradient: true,
                allowLegend: true,
                allowXAxis: true,
                allowYAxis: true,
                allowXScaleMin: false,
                allowXScaleMax: false,
                allowYScaleMin: false,
                allowYScaleMax: false,
                allowLabels: false,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: true,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false
            },
        ]
    },
    {
        name: 'Pie Charts',
        charts: [
            {
                key: eChartType.Pie, name: 'Pie Chart',
                inputFormat: eInputFormat.SingleSeries,
                isHorizontal: false,
                allowGradient: true,
                allowLegend: true,
                allowXAxis: false,
                allowYAxis: false,
                allowXScaleMin: false,
                allowXScaleMax: false,
                allowYScaleMin: false,
                allowYScaleMax: false,
                allowLabels: true,
                allowExplodeSlices: true,
                allowDoughnut: true,
                allowGridLines: false,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false
            },
            {
                key: eChartType.PieAdvanced, name: 'Pie Chart (Advanced)',
                inputFormat: eInputFormat.SingleSeries,
                isHorizontal: false,
                allowGradient: true,
                allowLegend: false,
                allowXAxis: false,
                allowYAxis: false,
                allowXScaleMin: false,
                allowXScaleMax: false,
                allowYScaleMin: false,
                allowYScaleMax: false,
                allowLabels: false,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: false,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false
            },
            {
                key: eChartType.PieGrid, name: 'Pie Chart (Grid)',
                inputFormat: eInputFormat.SingleSeries,
                isHorizontal: false,
                allowGradient: false,
                allowLegend: false,
                allowXAxis: false,
                allowYAxis: false,
                allowXScaleMin: false,
                allowXScaleMax: false,
                allowYScaleMin: false,
                allowYScaleMax: false,
                allowLabels: false,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: false,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false
            },
        ]
    },
    {
        name: 'Line/Area Charts',
        charts: [
            {
                key: eChartType.Line, name: 'Line Chart',
                inputFormat: eInputFormat.InverseSeries,
                isHorizontal: false,
                allowGradient: true,
                allowLegend: true,
                allowXAxis: true,
                allowYAxis: true,
                allowXScaleMin: false,
                allowXScaleMax: false,
                allowYScaleMin: true,
                allowYScaleMax: true,
                allowLabels: false,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: true,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false
            },
            {
                key: eChartType.Area, name: 'Area Chart',
                inputFormat: eInputFormat.InverseSeries,
                isHorizontal: false,
                allowGradient: true,
                allowLegend: true,
                allowXAxis: true,
                allowYAxis: true,
                allowXScaleMin: false,
                allowXScaleMax: false,
                allowYScaleMin: true,
                allowYScaleMax: true,
                allowLabels: false,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: true,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false
            },
            {
                key: eChartType.Polar, name: 'Polar Chart',
                inputFormat: eInputFormat.InverseSeries,
                isHorizontal: false,
                allowGradient: true,
                allowLegend: true,
                allowXAxis: true,
                allowYAxis: true,
                allowXScaleMin: false,
                allowXScaleMax: false,
                allowYScaleMin: false,
                allowYScaleMax: false,
                allowLabels: false,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: true,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false
            },
            {
                key: eChartType.AreaStacked, name: 'Area Stacked Chart',
                inputFormat: eInputFormat.InverseSeries,
                isHorizontal: false,
                allowGradient: true,
                allowLegend: true,
                allowXAxis: true,
                allowYAxis: true,
                allowXScaleMin: true,
                allowXScaleMax: true,
                allowYScaleMin: false,
                allowYScaleMax: false,
                allowLabels: false,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: true,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false
            },
            {
                key: eChartType.AreaNormalized, name: 'Area Normalized Chart',
                inputFormat: eInputFormat.InverseSeries,
                isHorizontal: false,
                allowGradient: true,
                allowLegend: true,
                allowXAxis: true,
                allowYAxis: true,
                allowXScaleMin: false,
                allowXScaleMax: false,
                allowYScaleMin: false,
                allowYScaleMax: false,
                allowLabels: false,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: true,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false
            },
        ]
    },
    {
        name: 'X-Y Charts',
        charts: [
            {
                key: eChartType.Scatter, name: 'X-Y Scatter Chart',
                inputFormat: eInputFormat.Xy,
                isHorizontal: false,
                allowGradient: false,
                allowLegend: true,
                allowXAxis: true,
                allowYAxis: true,
                allowXScaleMin: true,
                allowXScaleMax: true,
                allowYScaleMin: true,
                allowYScaleMax: true,
                allowLabels: false,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: true,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false
            },
            {
                key: eChartType.Error, name: 'X-Y Error Chart',
                inputFormat: eInputFormat.XyMinMax,
                isHorizontal: false,
                allowGradient: false,
                allowLegend: true,
                allowXAxis: true,
                allowYAxis: true,
                allowXScaleMin: true,
                allowXScaleMax: true,
                allowYScaleMin: true,
                allowYScaleMax: true,
                allowLabels: false,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: true,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false
            },
            {
                key: eChartType.Bubble, name: 'X-Y Bubble Chart',
                inputFormat: eInputFormat.XyBubble,
                isHorizontal: false,
                allowGradient: false,
                allowLegend: true,
                allowXAxis: true,
                allowYAxis: true,
                allowXScaleMin: true,
                allowXScaleMax: true,
                allowYScaleMin: true,
                allowYScaleMax: true,
                allowLabels: false,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: true,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false
            },
        ]
    },
    {
        name: 'Other Charts',
        charts: [
            {
                key: eChartType.HeatMap, name: 'Heat Map',
                inputFormat: eInputFormat.MultiSeries,
                isHorizontal: false,
                allowGradient: true,
                allowLegend: true,
                allowXAxis: true,
                allowYAxis: true,
                allowXScaleMin: true,
                allowXScaleMax: true,
                allowYScaleMin: false,
                allowYScaleMax: false,
                allowLabels: false,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: false,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: false,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'flame',
                defaultShowLegend: true
            },
            {
                key: eChartType.TreeMap, name: 'Tree Map',
                inputFormat: eInputFormat.SingleSeries,
                isHorizontal: false,
                allowGradient: true,
                allowLegend: false,
                allowXAxis: false,
                allowYAxis: false,
                allowXScaleMin: false,
                allowXScaleMax: false,
                allowYScaleMin: false,
                allowYScaleMax: false,
                allowLabels: false,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: true,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false
            },
            {
                key: eChartType.Cards, name: 'Number Cards',
                inputFormat: eInputFormat.SingleSeries,
                isHorizontal: false,
                allowGradient: false,
                allowLegend: false,
                allowXAxis: false,
                allowYAxis: false,
                allowXScaleMin: false,
                allowXScaleMax: false,
                allowYScaleMin: false,
                allowYScaleMax: false,
                allowLabels: false,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: false,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false
            },
            {
                key: eChartType.Gauge, name: 'Gauge',
                inputFormat: eInputFormat.SingleSeries,
                isHorizontal: false,
                allowGradient: false,
                allowLegend: true,
                allowXAxis: true,
                allowYAxis: false,
                allowXScaleMin: true,
                allowXScaleMax: true,
                allowYScaleMin: false,
                allowYScaleMax: false,
                allowLabels: false,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: false,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: true
            },
            {
                key: eChartType.LinearGauge, name: 'Linear Gauge',
                inputFormat: eInputFormat.SingleSeries,
                isHorizontal: false,
                allowGradient: false,
                allowLegend: true,
                allowXAxis: true,
                allowYAxis: false,
                allowXScaleMin: true,
                allowXScaleMax: true,
                allowYScaleMin: false,
                allowYScaleMax: false,
                allowLabels: false,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: false,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: true
            },
            {
                key: eChartType.Map, name: 'Google Map',
                inputFormat: eInputFormat.GeoCoordinates,
                isHorizontal: false,
                allowGradient: false,
                allowLegend: false,
                allowXAxis: false,
                allowYAxis: false,
                allowXScaleMin: false,
                allowXScaleMax: false,
                allowYScaleMin: false,
                allowYScaleMax: false,
                allowLabels: false,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: false,
                defaultShowXAxisLabel: false,
                defaultShowYAxisLabel: false,
                defaultShowXAxis: false,
                defaultShowYAxis: false,
                defaultShowGridLines: false,
                defaultColorScheme: 'natural',
                defaultShowLegend: false
            },

        ]
    }
]

// const ChartGroups = [
//     {
//       name: 'Bar Charts',
//       charts: [
//         {
//           name: 'Vertical Bar Chart',
//           selector: 'bar-vertical',
//           inputFormat: 'singleSeries',
//           options: [
//             'animations',
//             'colorScheme',
//             'schemeType',
//             'showXAxis',
//             'showYAxis',
//             'gradient',
//             'barPadding',
//             'showLegend',
//             'legendTitle',
//             'legendPosition',
//             'showXAxisLabel',
//             'xAxisLabel',
//             'showYAxisLabel',
//             'yAxisLabel',
//             'showGridLines',
//             'roundDomains',
//             'tooltipDisabled',
//             'roundEdges',
//             'yScaleMax',
//             'showDataLabel'
//           ]
//         },
//         {
//             name: 'Horizontal Bar Chart',
//           selector: 'bar-horizontal',
//           inputFormat: 'singleSeries',
//           options: [
//             'animations',
//             'colorScheme',
//             'schemeType',
//             'showXAxis',
//             'showYAxis',
//             'gradient',
//             'barPadding',
//             'showLegend',
//             'legendTitle',
//             'legendPosition',
//             'showXAxisLabel',
//             'xAxisLabel',
//             'showYAxisLabel',
//             'yAxisLabel',
//             'showGridLines',
//             'roundDomains',
//             'tooltipDisabled',
//             'roundEdges',
//             'xScaleMax',
//             'showDataLabel'
//           ],
//           defaults: {
//             yAxisLabel: 'Country',
//             xAxisLabel: 'GDP Per Capita'
//           }
//         },
//         {
//           name: 'Grouped Vertical Bar Chart',
//           selector: 'bar-vertical-2d',
//           inputFormat: 'multiSeries',
//           options: [
//             'animations',
//             'colorScheme',
//             'schemeType',
//             'showXAxis',
//             'showYAxis',
//             'gradient',
//             'barPadding',
//             'groupPadding',
//             'showLegend',
//             'legendTitle',
//             'legendPosition',
//             'showXAxisLabel',
//             'xAxisLabel',
//             'showYAxisLabel',
//             'yAxisLabel',
//             'showGridLines',
//             'roundDomains',
//             'tooltipDisabled',
//             'roundEdges',
//             'yScaleMax',
//             'showDataLabel'
//           ]
//         },
//         {
//           name: 'Grouped Horizontal Bar Chart',
//           selector: 'bar-horizontal-2d',
//           inputFormat: 'multiSeries',
//           options: [
//             'animations',
//             'colorScheme',
//             'schemeType',
//             'showXAxis',
//             'showYAxis',
//             'gradient',
//             'barPadding',
//             'groupPadding',
//             'showLegend',
//             'legendTitle',
//             'legendPosition',
//             'showXAxisLabel',
//             'xAxisLabel',
//             'showYAxisLabel',
//             'yAxisLabel',
//             'showGridLines',
//             'roundDomains',
//             'tooltipDisabled',
//             'roundEdges',
//             'xScaleMax',
//             'showDataLabel'
//           ],
//           defaults: {
//             yAxisLabel: 'Country',
//             xAxisLabel: 'GDP Per Capita'
//           }
//         },
//         {
//           name: 'Stacked Vertical Bar Chart',
//           selector: 'bar-vertical-stacked',
//           inputFormat: 'multiSeries',
//           options: [
//             'animations',
//             'colorScheme',
//             'schemeType',
//             'showXAxis',
//             'showYAxis',
//             'gradient',
//             'barPadding',
//             'showLegend',
//             'legendTitle',
//             'legendPosition',
//             'showXAxisLabel',
//             'xAxisLabel',
//             'showYAxisLabel',
//             'yAxisLabel',
//             'showGridLines',
//             'roundDomains',
//             'tooltipDisabled',
//             'yScaleMax',
//             'showDataLabel'
//           ]
//         },
//         {
//           name: 'Stacked Horizontal Bar Chart',
//           selector: 'bar-horizontal-stacked',
//           inputFormat: 'multiSeries',
//           options: [
//             'animations',
//             'colorScheme',
//             'schemeType',
//             'showXAxis',
//             'showYAxis',
//             'gradient',
//             'barPadding',
//             'showLegend',
//             'legendTitle',
//             'legendPosition',
//             'showXAxisLabel',
//             'xAxisLabel',
//             'showYAxisLabel',
//             'yAxisLabel',
//             'showGridLines',
//             'roundDomains',
//             'tooltipDisabled',
//             'xScaleMax',
//             'showDataLabel'
//           ],
//           defaults: {
//             yAxisLabel: 'Country',
//             xAxisLabel: 'GDP Per Capita'
//           }
//         },
//         {
//           name: 'Normalized Vertical Bar Chart',
//           selector: 'bar-vertical-normalized',
//           inputFormat: 'multiSeries',
//           options: [
//             'animations',
//             'colorScheme',
//             'schemeType',
//             'showXAxis',
//             'showYAxis',
//             'gradient',
//             'barPadding',
//             'showLegend',
//             'legendTitle',
//             'legendPosition',
//             'showXAxisLabel',
//             'xAxisLabel',
//             'showYAxisLabel',
//             'yAxisLabel',
//             'showGridLines',
//             'roundDomains',
//             'tooltipDisabled'
//           ],
//           defaults: {
//             yAxisLabel: 'Normalized GDP Per Capita',
//             xAxisLabel: 'Country'
//           }
//         },
//         {
//           name: 'Normalized Horizontal Bar Chart',
//           selector: 'bar-horizontal-normalized',
//           inputFormat: 'multiSeries',
//           options: [
//             'animations',
//             'colorScheme',
//             'schemeType',
//             'showXAxis',
//             'showYAxis',
//             'gradient',
//             'barPadding',
//             'showLegend',
//             'legendTitle',
//             'legendPosition',
//             'showXAxisLabel',
//             'xAxisLabel',
//             'showYAxisLabel',
//             'yAxisLabel',
//             'showGridLines',
//             'roundDomains',
//             'tooltipDisabled'
//           ],
//           defaults: {
//             yAxisLabel: 'Country',
//             xAxisLabel: 'Normalized GDP Per Capita'
//           }
//         }
//       ]
//     },
//     {
//       name: 'Pie Charts',
//       charts: [
//         {
//           name: 'Pie Chart',
//           selector: 'pie-chart',
//           inputFormat: 'singleSeries',
//           options: [
//             'animations',
//             'colorScheme',
//             'gradient',
//             'showLegend',
//             'legendTitle',
//             'legendPosition',
//             'doughnut',
//             'arcWidth',
//             'explodeSlices',
//             'showLabels',
//             'tooltipDisabled'
//           ]
//         },
//         {
//           name: 'Advanced Pie Chart',
//           selector: 'advanced-pie-chart',
//           inputFormat: 'singleSeries',
//           options: ['animations', 'colorScheme', 'gradient', 'tooltipDisabled']
//         },
//         {
//           name: 'Pie Grid',
//           selector: 'pie-grid',
//           inputFormat: 'singleSeries',
//           options: ['animations', 'colorScheme', 'tooltipDisabled']
//         }
//       ]
//     },
//     {
//       name: 'Line/Area Charts',
//       charts: [
//         {
//           name: 'Line Chart',
//           selector: 'line-chart',
//           inputFormat: 'inverseMultiSeries',
//           options: [
//             'animations',
//             'colorScheme',
//             'schemeType',
//             'showXAxis',
//             'showYAxis',
//             'gradient',
//             'showLegend',
//             'legendTitle',
//             'legendPosition',
//             'showXAxisLabel',
//             'xAxisLabel',
//             'showYAxisLabel',
//             'yAxisLabel',
//             'autoScale',
//             'timeline',
//             'showGridLines',
//             'curve',
//             'rangeFillOpacity',
//             'roundDomains',
//             'tooltipDisabled',
//             'showRefLines',
//             'referenceLines',
//             'showRefLabels',
//             'xScaleMin',
//             'xScaleMax',
//             'yScaleMin',
//             'yScaleMax'
//           ],
//           defaults: {
//             yAxisLabel: 'GDP Per Capita',
//             xAxisLabel: 'Census Date',
//             linearScale: true
//           }
//         },
//         {
//           name: 'Polar Chart',
//           selector: 'polar-chart',
//           inputFormat: 'inverseMultiSeries',
//           options: [
//             'animations',
//             'colorScheme',
//             'schemeType',
//             'showXAxis',
//             'showYAxis',
//             'gradient',
//             'showLegend',
//             'legendTitle',
//             'legendPosition',
//             'showXAxisLabel',
//             'xAxisLabel',
//             'showYAxisLabel',
//             'yAxisLabel',
//             'autoScale',
//             'showGridLines',
//             'curveClosed',
//             'roundDomains',
//             'tooltipDisabled'
//           ],
//           defaults: {
//             yAxisLabel: 'GDP Per Capita',
//             xAxisLabel: 'Census Date',
//             linearScale: true
//           }
//         },
//         {
//           name: 'Area Chart',
//           selector: 'area-chart',
//           inputFormat: 'inverseMultiSeries',
//           options: [
//             'animations',
//             'colorScheme',
//             'schemeType',
//             'showXAxis',
//             'showYAxis',
//             'gradient',
//             'showLegend',
//             'legendTitle',
//             'legendPosition',
//             'showXAxisLabel',
//             'xAxisLabel',
//             'showYAxisLabel',
//             'yAxisLabel',
//             'autoScale',
//             'timeline',
//             'showGridLines',
//             'curve',
//             'roundDomains',
//             'tooltipDisabled',
//             'xScaleMin',
//             'xScaleMax',
//             'yScaleMin',
//             'yScaleMax'
//           ],
//           defaults: {
//             yAxisLabel: 'GDP Per Capita',
//             xAxisLabel: 'Census Date',
//             linearScale: true
//           }
//         },
//         {
//           name: 'Stacked Area Chart',
//           selector: 'area-chart-stacked',
//           inputFormat: 'inverseMultiSeries',
//           options: [
//             'animations',
//             'colorScheme',
//             'schemeType',
//             'showXAxis',
//             'showYAxis',
//             'gradient',
//             'showLegend',
//             'legendTitle',
//             'legendPosition',
//             'showXAxisLabel',
//             'xAxisLabel',
//             'showYAxisLabel',
//             'yAxisLabel',
//             'autoScale',
//             'timeline',
//             'showGridLines',
//             'curve',
//             'roundDomains',
//             'tooltipDisabled',
//             'xScaleMin',
//             'xScaleMax',
//             'yScaleMin',
//             'yScaleMax'
//           ],
//           defaults: {
//             yAxisLabel: 'GDP Per Capita',
//             xAxisLabel: 'Census Date',
//             linearScale: true
//           }
//         },
//         {
//           name: 'Normalized Area Chart',
//           selector: 'area-chart-normalized',
//           inputFormat: 'inverseMultiSeries',
//           options: [
//             'animations',
//             'colorScheme',
//             'schemeType',
//             'showXAxis',
//             'showYAxis',
//             'gradient',
//             'showLegend',
//             'legendTitle',
//             'legendPosition',
//             'showXAxisLabel',
//             'xAxisLabel',
//             'showYAxisLabel',
//             'yAxisLabel',
//             'autoScale',
//             'timeline',
//             'showGridLines',
//             'curve',
//             'roundDomains',
//             'tooltipDisabled'
//           ],
//           defaults: {
//             yAxisLabel: 'Normalized GDP Per Capita',
//             xAxisLabel: 'Census Date',
//             linearScale: true
//           }
//         }
//       ]
//     },
//     {
//       name: 'Other Charts',
//       charts: [
//         {
//           name: 'Bubble Chart',
//           selector: 'bubble-chart',
//           inputFormat: 'bubble',
//           options: [
//             'animations',
//             'colorScheme',
//             'schemeType',
//             'showXAxis',
//             'showYAxis',
//             'showLegend',
//             'legendTitle',
//             'legendPosition',
//             'showXAxisLabel',
//             'xAxisLabel',
//             'showYAxisLabel',
//             'yAxisLabel',
//             'showGridLines',
//             'roundDomains',
//             'autoScale',
//             'minRadius',
//             'maxRadius',
//             'tooltipDisabled',
//             'xScaleMin',
//             'xScaleMax',
//             'yScaleMin',
//             'yScaleMax'
//           ],
//           defaults: {
//             xAxisLabel: 'Census Date',
//             yAxisLabel: 'Life expectancy [years]'
//           }
//         },
//         {
//           name: 'Force Directed Graph',
//           selector: 'force-directed-graph',
//           inputFormat: 'graph',
//           options: [
//             'animations', 'colorScheme', 'showLegend', 'legendTitle',
//             'legendPosition', 'tooltipDisabled'
//           ]
//         },
//         {
//           name: 'Heat Map',
//           selector: 'heat-map',
//           inputFormat: 'multiSeries',
//           options: [
//             'animations',
//             'colorScheme',
//             'showXAxis',
//             'showYAxis',
//             'gradient',
//             'showLegend',
//             'showXAxisLabel',
//             'xAxisLabel',
//             'showYAxisLabel',
//             'yAxisLabel',
//             'innerPadding',
//             'tooltipDisabled',
//             'min',
//             'max',
//           ],
//           defaults: {
//             yAxisLabel: 'Census Date',
//             cAxisLabel: 'Country'
//           }
//         },
//         {
//           name: 'Tree Map',
//           selector: 'tree-map',
//           inputFormat: 'singleSeries',
//           options: ['animations', 'colorScheme', 'tooltipDisabled', 'gradient']
//         },
//         {
//           name: 'Number Cards',
//           selector: 'number-card',
//           inputFormat: 'singleSeries',
//           options: ['animations', 'colorScheme']
//         },
//         {
//           name: 'Gauge',
//           selector: 'gauge',
//           inputFormat: 'singleSeries',
//           options: [
//             'showLegend',
//             'legendTitle',
//             'legendPosition',
//             'colorScheme',
//             'min',
//             'max',
//             'largeSegments',
//             'smallSegments',
//             'units',
//             'angleSpan',
//             'startAngle',
//             'showAxis',
//             'margin',
//             'tooltipDisabled',
//             'animations'
//           ]
//         },
//         {
//           name: 'Linear Gauge',
//           selector: 'linear-gauge',
//           inputFormat: 'single',
//           options: ['animations', 'colorScheme', 'value', 'previousValue', 'min', 'max', 'units']
//         }
//       ]
//     },
//     {
//       name: 'Demos',
//       charts: [
//         {
//           name: 'Combo Chart',
//           selector: 'combo-chart',
//           inputFormat: 'comboChart',
//           options: [
//             'animations',
//             'showXAxis',
//             'showYAxis',
//             'gradient',
//             'showLegend',
//             'legendTitle',
//             'legendPosition',
//             'showXAxisLabel',
//             'xAxisLabel',
//             'showYAxisLabel',
//             'yAxisLabel',
//             'showGridLines',
//             'roundDomains',
//             'tooltipDisabled'
//           ]
//         },
//         {
//           name: 'Heat Map - Calendar',
//           selector: 'calendar',
//           inputFormat: 'calendarData',
//           options: [
//             'animations',
//             'colorScheme',
//             'showXAxis',
//             'showYAxis',
//             'gradient',
//             'showLegend',
//             'innerPadding',
//             'tooltipDisabled'
//           ],
//           defaults: {
//             width: 1100,
//             height: 200
//           }
//         },
//         {
//           name: 'Number Cards - Status',
//           selector: 'status-demo',
//           inputFormat: 'statusData',
//           options: ['animations', 'colorScheme']
//         },
//         {
//           name: 'TreeMap - Interactive',
//           selector: 'tree-map-demo',
//           inputFormat: 'treemap',
//           options: ['animations', 'colorScheme']
//         },
//         {
//           name: 'Equation Plots',
//           selector: 'plot-demo',
//           inputFormat: 'statusData',
//           options: [
//             'animations',
//             'colorScheme',
//             'schemeType',
//             'showXAxis',
//             'showYAxis',
//             'autoScale',
//             'showGridLines',
//             'gradient',
//             'roundDomains',
//             'tooltipDisabled'
//           ]
//         },
//         {
//           name: 'Tooltip Templates',
//           selector: 'tooltip-templates',
//           inputFormat: 'singleSeries',
//           options: [
//             'animations',
//             'colorScheme',
//             'schemeType',
//             'showXAxis',
//             'showYAxis',
//             'gradient',
//             'barPadding',
//             'showLegend',
//             'legendTitle',
//             'legendPosition',
//             'showXAxisLabel',
//             'xAxisLabel',
//             'showYAxisLabel',
//             'yAxisLabel',
//             'showGridLines',
//             'roundDomains',
//             'tooltipDisabled'
//           ]
//         },
//         {
//           name: 'Sparklines',
//           selector: 'sparkline',
//           inputFormat: 'multiSeries',
//           options: ['animations', 'curve']
//         },
//         {
//           name: 'Line Chart with Reference Lines',
//           selector: 'line-reference-lines',
//           inputFormat: 'multiSeries',
//           options: [
//             'animations',
//             'colorScheme',
//             'schemeType',
//             'showXAxis',
//             'showYAxis',
//             'gradient',
//             'showLegend',
//             'legendTitle',
//             'legendPosition',
//             'showXAxisLabel',
//             'xAxisLabel',
//             'showYAxisLabel',
//             'yAxisLabel',
//             'autoScale',
//             'timeline',
//             'showGridLines',
//             'curve',
//             'rangeFillOpacity',
//             'roundDomains',
//             'tooltipDisabled',
//             'showRefLines',
//             'referenceLines',
//             'showRefLabels'
//           ],
//           defaults: {
//             yAxisLabel: 'GDP Per Capita',
//             xAxisLabel: 'Year',
//             linearScale: false
//           }
//         },
//         {
//           name: 'Timeline Filter Bar Chart',
//           selector: 'timeline-filter-bar-chart-demo',
//           inputFormat: 'singleSeries',
//           options: [
//             'animations',
//             'colorScheme',
//             'schemeType',
//             'showXAxis',
//             'showYAxis',
//             'gradient',
//             'showGridLines',
//             'showXAxisLabel',
//             'xAxisLabel',
//             'showYAxisLabel',
//             'yAxisLabel'
//           ]
//         },
//         {
//           name: 'Stacked Vertical Bar Chart Negative',
//           selector: 'bar-vertical-stacked-negative',
//           inputFormat: 'multiSeriesNegative',
//           options: [
//             'animations',
//             'colorScheme',
//             'schemeType',
//             'showXAxis',
//             'showYAxis',
//             'gradient',
//             'barPadding',
//             'showLegend',
//             'legendTitle',
//             'legendPosition',
//             'showXAxisLabel',
//             'xAxisLabel',
//             'showYAxisLabel',
//             'yAxisLabel',
//             'showGridLines',
//             'roundDomains',
//             'tooltipDisabled',
//             'yScaleMax',
//             'showDataLabel'
//           ]
//         },
//         {
//           name: 'Stacked Horizontal Bar Chart Negative',
//           selector: 'bar-horizontal-stacked-negative',
//           inputFormat: 'multiSeriesNegative',
//           options: [
//             'animations',
//             'colorScheme',
//             'schemeType',
//             'showXAxis',
//             'showYAxis',
//             'gradient',
//             'barPadding',
//             'showLegend',
//             'legendTitle',
//             'legendPosition',
//             'showXAxisLabel',
//             'xAxisLabel',
//             'showYAxisLabel',
//             'yAxisLabel',
//             'showGridLines',
//             'roundDomains',
//             'tooltipDisabled',
//             'yScaleMax',
//             'showDataLabel'
//           ]
//         }
//       ]
//     }
//   ];

//   export default ChartGroups;
