import { ChartDataSets } from 'chart.js';
import { Label } from 'ng2-charts';
import { eChartType } from '../../shared.models';

export enum eInputFormat {
    SingleSeries,
    MultiSeries,
    ComboSeries,
    InverseSeries,
    Xy,
    XyMinMax,
    XyBubble,
 //   GeoCoordinates
}

export const inputFormats = [
{key: eInputFormat.SingleSeries, allowLabel: true, maxSeries: 1, allowYSeries: false,
    allowMinMax: false, allowBubble: false, inverse: false },
{key: eInputFormat.MultiSeries, allowLabel: true, maxSeries: 10, allowYSeries: false,
    allowMinMax: false, allowBubble: false, inverse: false },
{key: eInputFormat.ComboSeries, allowLabel: true, maxSeries: 10, allowYSeries: false,
    allowMinMax: false, allowBubble: false, inverse: false },
{key: eInputFormat.InverseSeries, allowLabel: true, maxSeries: 10, allowYSeries: false,
    allowMinMax: false, allowBubble: false, inverse: true },
{key: eInputFormat.Xy, allowLabel: false, maxSeries: 1, allowYSeries: true,
    allowMinMax: false, allowBubble: false, inverse: false },
{key: eInputFormat.XyMinMax, allowLabel: false, maxSeries: 1, allowYSeries: true,
    allowMinMax: true, allowBubble: false, inverse: false },
{key: eInputFormat.XyBubble, allowLabel: false, maxSeries: 1, allowYSeries: true,
    allowMinMax: false, allowBubble: true, inverse: false },
]


export class ChartItem {
    public name: string;
    public labels: Label[];
    public dataSets: ChartDataSets[];
    public data: ChartDataSets[];
}

export class ChartType {
    public key: eChartType;
    public name: string;
    public type: string;
    public inputFormat: eInputFormat;
    public isHorizontal = false;
    public allowGradient = true;
    public allowLegend = true;
    public allowXAxis = true;
    public allowYAxis = true;
    public allowXScaleMin = false;
    public allowXScaleMax = false;
    public allowYScaleMin = true;
    public allowYScaleMax = true;
    public allowLabels = true;
    public allowExplodeSlices = false;
    public allowDoughnut = false;
    public allowGridLines = true;
    public defaultShowXAxisLabel = true;
    public defaultShowYAxisLabel = true;
    public defaultShowXAxis = true;
    public defaultShowYAxis = true;
    public defaultShowGridLines = true;
    public defaultColorScheme = 'natural';
    public defaultShowLegend = false;
    public defaultShowLabels = false;
    public isBar = true;
}

export const ChartTypes = [
    {
        name: 'Bar Charts',
        charts: [
            {
                key: eChartType.BarVertical, name: 'Vertical Bar Chart',
                type: 'bar',
                inputFormat: eInputFormat.MultiSeries,
                isHorizontal: false,
                allowGradient: true,
                allowLegend: true,
                allowXAxis: true,
                allowYAxis: true,
                allowXScaleMin: false,
                allowXScaleMax: false,
                allowYScaleMin: true,
                allowYScaleMax: true,
                allowLabels: true,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: true,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false,
                defaultShowLabels: false,
                isBar: true,
                isLine: true
            },
            {
                key: eChartType.BarHorizontal, name: 'Horizontal Bar Chart',
                type: 'horizontalBar',
                inputFormat: eInputFormat.MultiSeries,
                isHorizontal: true,
                allowGradient: true,
                allowLegend: true,
                allowXAxis: true,
                allowYAxis: true,
                allowXScaleMin: true,
                allowXScaleMax: true,
                allowYScaleMin: false,
                allowYScaleMax: false,
                allowLabels: true,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: true,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false,
                defaultShowLabels: false,
                isBar: true,
                isLine: false
            },
            // {
            //     key: eChartType.BarVertical2D, name: 'Vertical Bar Chart (MultiSeries)',
            //     type: 'bar',
            //     inputFormat: eInputFormat.MultiSeries,
            //     isHorizontal: false,
            //     allowGradient: true,
            //     allowLegend: true,
            //     allowXAxis: true,
            //     allowYAxis: true,
            //     allowXScaleMin: false,
            //     allowXScaleMax: false,
            //     allowYScaleMin: false,
            //     allowYScaleMax: true,
            //     allowLabels: false,
            //     allowExplodeSlices: false,
            //     allowDoughnut: false,
            //     allowGridLines: true,
            //     defaultShowXAxisLabel: true,
            //     defaultShowYAxisLabel: true,
            //     defaultShowXAxis: true,
            //     defaultShowYAxis: true,
            //     defaultShowGridLines: true,
            //     defaultColorScheme: 'natural',
            //     defaultShowLegend: false,
            //     isBar: true
            // },
            // {
            //     key: eChartType.BarHorizontal2D, name: 'Horizontal Bar Chart (MultiSeries)',
            //     type: 'horizontalBar',
            //     inputFormat: eInputFormat.MultiSeries,
            //     isHorizontal: true,
            //     allowGradient: true,
            //     allowLegend: true,
            //     allowXAxis: true,
            //     allowYAxis: true,
            //     allowXScaleMin: false,
            //     allowXScaleMax: true,
            //     allowYScaleMin: false,
            //     allowYScaleMax: false,
            //     allowLabels: false,
            //     allowExplodeSlices: false,
            //     allowDoughnut: false,
            //     allowGridLines: true,
            //     defaultShowXAxisLabel: true,
            //     defaultShowYAxisLabel: true,
            //     defaultShowXAxis: true,
            //     defaultShowYAxis: true,
            //     defaultShowGridLines: true,
            //     defaultColorScheme: 'natural',
            //     defaultShowLegend: false,
            //     isBar: true
            // },
            // {
            //     key: eChartType.BarVerticalStacked, name: 'Vertical Stacked Bar Chart',
            //     inputFormat: eInputFormat.MultiSeries,
            //     isHorizontal: false,
            //     allowGradient: true,
            //     allowLegend: true,
            //     allowXAxis: true,
            //     allowYAxis: true,
            //     allowXScaleMin: false,
            //     allowXScaleMax: false,
            //     allowYScaleMin: false,
            //     allowYScaleMax: true,
            //     allowLabels: false,
            //     allowExplodeSlices: false,
            //     allowDoughnut: false,
            //     allowGridLines: true,
            //     defaultShowXAxisLabel: true,
            //     defaultShowYAxisLabel: true,
            //     defaultShowXAxis: true,
            //     defaultShowYAxis: true,
            //     defaultShowGridLines: true,
            //     defaultColorScheme: 'natural',
            //     defaultShowLegend: false,
            //     isBar: true
            // },
            // {
            //     key: eChartType.BarHorizontalStacked, name: 'Horizontal Stacked Bar Chart',
            //     inputFormat: eInputFormat.MultiSeries,
            //     isHorizontal: true,
            //     allowGradient: true,
            //     allowLegend: true,
            //     allowXAxis: true,
            //     allowYAxis: true,
            //     allowXScaleMin: false,
            //     allowXScaleMax: true,
            //     allowYScaleMin: false,
            //     allowYScaleMax: false,
            //     allowLabels: false,
            //     allowExplodeSlices: false,
            //     allowDoughnut: false,
            //     allowGridLines: true,
            //     defaultShowXAxisLabel: true,
            //     defaultShowYAxisLabel: true,
            //     defaultShowXAxis: true,
            //     defaultShowYAxis: true,
            //     defaultShowGridLines: true,
            //     defaultColorScheme: 'natural',
            //     defaultShowLegend: false,
            //     isBar: true
            // },
            // {
            //     key: eChartType.BarVerticalNormalized, name: 'Vertical Normalized Bar Chart',
            //     inputFormat: eInputFormat.MultiSeries,
            //     isHorizontal: false,
            //     allowGradient: true,
            //     allowLegend: true,
            //     allowXAxis: true,
            //     allowYAxis: true,
            //     allowXScaleMin: false,
            //     allowXScaleMax: false,
            //     allowYScaleMin: false,
            //     allowYScaleMax: false,
            //     allowLabels: false,
            //     allowExplodeSlices: false,
            //     allowDoughnut: false,
            //     allowGridLines: true,
            //     defaultShowXAxisLabel: true,
            //     defaultShowYAxisLabel: true,
            //     defaultShowXAxis: true,
            //     defaultShowYAxis: true,
            //     defaultShowGridLines: true,
            //     defaultColorScheme: 'natural',
            //     defaultShowLegend: false,
            //     isBar: true
            // },
            // {
            //     key: eChartType.BarHorizontalNormalized, name: 'Horizontal Normalized Bar Chart',
            //     inputFormat: eInputFormat.MultiSeries,
            //     isHorizontal: true,
            //     allowGradient: true,
            //     allowLegend: true,
            //     allowXAxis: true,
            //     allowYAxis: true,
            //     allowXScaleMin: false,
            //     allowXScaleMax: false,
            //     allowYScaleMin: false,
            //     allowYScaleMax: false,
            //     allowLabels: false,
            //     allowExplodeSlices: false,
            //     allowDoughnut: false,
            //     allowGridLines: true,
            //     defaultShowXAxisLabel: true,
            //     defaultShowYAxisLabel: true,
            //     defaultShowXAxis: true,
            //     defaultShowYAxis: true,
            //     defaultShowGridLines: true,
            //     defaultColorScheme: 'natural',
            //     defaultShowLegend: false,
            //     isBar: true
            // },
        ]
    },
    {
        name: 'Pie Charts',
        charts: [
            {
                key: eChartType.Pie, name: 'Pie Chart',
                type:'pie',
                inputFormat: eInputFormat.MultiSeries,
                isHorizontal: false,
                allowGradient: true,
                allowLegend: true,
                allowXAxis: false,
                allowYAxis: false,
                allowXScaleMin: false,
                allowXScaleMax: false,
                allowYScaleMin: false,
                allowYScaleMax: false,
                allowLabels: true,
                allowExplodeSlices: true,
                allowDoughnut: true,
                allowGridLines: false,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false,
                defaultShowLabels: true,
                isBar: false,
                isLine: false
            },
            // {
            //     key: eChartType.Pie, name: 'Doughnut',
            //     type:'doughnut',
            //     inputFormat: eInputFormat.MultiSeries,
            //     isHorizontal: false,
            //     allowGradient: true,
            //     allowLegend: true,
            //     allowXAxis: false,
            //     allowYAxis: false,
            //     allowXScaleMin: false,
            //     allowXScaleMax: false,
            //     allowYScaleMin: false,
            //     allowYScaleMax: false,
            //     allowLabels: true,
            //     allowExplodeSlices: true,
            //     allowDoughnut: true,
            //     allowGridLines: false,
            //     defaultShowXAxisLabel: true,
            //     defaultShowYAxisLabel: true,
            //     defaultShowXAxis: true,
            //     defaultShowYAxis: true,
            //     defaultShowGridLines: true,
            //     defaultColorScheme: 'natural',
            //     defaultShowLegend: false,
            //     isBar: false
            // },
            // {
            //     key: eChartType.PieAdvanced, name: 'Pie Chart (Advanced)',
            //     inputFormat: eInputFormat.SingleSeries,
            //     isHorizontal: false,
            //     allowGradient: true,
            //     allowLegend: false,
            //     allowXAxis: false,
            //     allowYAxis: false,
            //     allowXScaleMin: false,
            //     allowXScaleMax: false,
            //     allowYScaleMin: false,
            //     allowYScaleMax: false,
            //     allowLabels: false,
            //     allowExplodeSlices: false,
            //     allowDoughnut: false,
            //     allowGridLines: false,
            //     defaultShowXAxisLabel: true,
            //     defaultShowYAxisLabel: true,
            //     defaultShowXAxis: true,
            //     defaultShowYAxis: true,
            //     defaultShowGridLines: true,
            //     defaultColorScheme: 'natural',
            //     defaultShowLegend: false,
            //     isBar: false
            // },
            // {
            //     key: eChartType.PieGrid, name: 'Pie Chart (Grid)',
            //     inputFormat: eInputFormat.SingleSeries,
            //     isHorizontal: false,
            //     allowGradient: false,
            //     allowLegend: false,
            //     allowXAxis: false,
            //     allowYAxis: false,
            //     allowXScaleMin: false,
            //     allowXScaleMax: false,
            //     allowYScaleMin: false,
            //     allowYScaleMax: false,
            //     allowLabels: false,
            //     allowExplodeSlices: false,
            //     allowDoughnut: false,
            //     allowGridLines: false,
            //     defaultShowXAxisLabel: true,
            //     defaultShowYAxisLabel: true,
            //     defaultShowXAxis: true,
            //     defaultShowYAxis: true,
            //     defaultShowGridLines: true,
            //     defaultColorScheme: 'natural',
            //     defaultShowLegend: false,
            //     isBar: false
            // },
        ]
    },
    {
        name: 'Line/Area Charts',
        charts: [
            {
                key: eChartType.Line, name: 'Line Chart',
                type: 'line',
                inputFormat: eInputFormat.MultiSeries,
                isHorizontal: false,
                allowGradient: true,
                allowLegend: true,
                allowXAxis: true,
                allowYAxis: true,
                allowXScaleMin: false,
                allowXScaleMax: false,
                allowYScaleMin: true,
                allowYScaleMax: true,
                allowLabels: true,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowFill: true,
                allowGridLines: true,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false,
                defaultShowLabels: false,
                isBar: false,
                isLine: true
            },
            // {
            //     key: eChartType.Area, name: 'Area Chart',
            //     inputFormat: eInputFormat.InverseSeries,
            //     isHorizontal: false,
            //     allowGradient: true,
            //     allowLegend: true,
            //     allowXAxis: true,
            //     allowYAxis: true,
            //     allowXScaleMin: false,
            //     allowXScaleMax: false,
            //     allowYScaleMin: true,
            //     allowYScaleMax: true,
            //     allowLabels: false,
            //     allowExplodeSlices: false,
            //     allowDoughnut: false,
            //     allowGridLines: true,
            //     defaultShowXAxisLabel: true,
            //     defaultShowYAxisLabel: true,
            //     defaultShowXAxis: true,
            //     defaultShowYAxis: true,
            //     defaultShowGridLines: true,
            //     defaultColorScheme: 'natural',
            //     defaultShowLegend: false,
            //     isBar: false
            // },
            {
                key: eChartType.Polar, name: 'Polar Area Chart',
                type: 'polarArea',
                inputFormat: eInputFormat.MultiSeries,
                isHorizontal: false,
                allowGradient: true,
                allowLegend: true,
                allowXAxis: false,
                allowYAxis: false,
                allowXScaleMin: false,
                allowXScaleMax: false,
                allowYScaleMin: false,
                allowYScaleMax: false,
                allowLabels: true,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowFill: false,
                allowGridLines: true,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false,
                defaultShowLabels: true,
                isBar: false,
                isLine: false
            },
            {
                key: eChartType.Radar, name: 'Radar Chart',
                type: 'radar',
                inputFormat: eInputFormat.MultiSeries,
                isHorizontal: false,
                allowGradient: true,
                allowLegend: true,
                allowXAxis: false,
                allowYAxis: false,
                allowXScaleMin: false,
                allowXScaleMax: false,
                allowYScaleMin: false,
                allowYScaleMax: false,
                allowLabels: true,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowFill: true,
                allowGridLines: true,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false,
                defaultShowLabels: true,
                isBar: false,
                isLine: false
            },
            // {
            //     key: eChartType.AreaStacked, name: 'Area Stacked Chart',
            //     inputFormat: eInputFormat.InverseSeries,
            //     isHorizontal: false,
            //     allowGradient: true,
            //     allowLegend: true,
            //     allowXAxis: true,
            //     allowYAxis: true,
            //     allowXScaleMin: true,
            //     allowXScaleMax: true,
            //     allowYScaleMin: false,
            //     allowYScaleMax: false,
            //     allowLabels: false,
            //     allowExplodeSlices: false,
            //     allowDoughnut: false,
            //     allowGridLines: true,
            //     defaultShowXAxisLabel: true,
            //     defaultShowYAxisLabel: true,
            //     defaultShowXAxis: true,
            //     defaultShowYAxis: true,
            //     defaultShowGridLines: true,
            //     defaultColorScheme: 'natural',
            //     defaultShowLegend: false,
            //     isBar: false
            // },
            // {
            //     key: eChartType.AreaNormalized, name: 'Area Normalized Chart',
            //     inputFormat: eInputFormat.InverseSeries,
            //     isHorizontal: false,
            //     allowGradient: true,
            //     allowLegend: true,
            //     allowXAxis: true,
            //     allowYAxis: true,
            //     allowXScaleMin: false,
            //     allowXScaleMax: false,
            //     allowYScaleMin: false,
            //     allowYScaleMax: false,
            //     allowLabels: false,
            //     allowExplodeSlices: false,
            //     allowDoughnut: false,
            //     allowGridLines: true,
            //     defaultShowXAxisLabel: true,
            //     defaultShowYAxisLabel: true,
            //     defaultShowXAxis: true,
            //     defaultShowYAxis: true,
            //     defaultShowGridLines: true,
            //     defaultColorScheme: 'natural',
            //     defaultShowLegend: false,
            //     isBar: false
            // },
        ]
    },
    {
        name: 'X-Y Charts',
        charts: [
            {
                key: eChartType.Scatter, name: 'X-Y Scatter Chart',
                type: 'scatter',
                inputFormat: eInputFormat.Xy,
                isHorizontal: false,
                allowGradient: false,
                allowLegend: true,
                allowXAxis: true,
                allowYAxis: true,
                allowXScaleMin: true,
                allowXScaleMax: true,
                allowYScaleMin: true,
                allowYScaleMax: true,
                allowLabels: false,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: true,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false,
                defaultShowLabels: false,
                isBar: false,
                isLine: false
            },
            {
                key: eChartType.Error, name: 'X-Y Error Chart',
                inputFormat: eInputFormat.XyMinMax,
                isHorizontal: false,
                allowGradient: false,
                allowLegend: true,
                allowXAxis: true,
                allowYAxis: true,
                allowXScaleMin: true,
                allowXScaleMax: true,
                allowYScaleMin: true,
                allowYScaleMax: true,
                allowLabels: false,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: true,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false,
                defaultShowLabels: false,
                isBar: false,
                isLine: false
            },
            {
                key: eChartType.Bubble, name: 'X-Y Bubble Chart',
                type: 'bubble',
                inputFormat: eInputFormat.XyBubble,
                isHorizontal: false,
                allowGradient: false,
                allowLegend: true,
                allowXAxis: true,
                allowYAxis: true,
                allowXScaleMin: true,
                allowXScaleMax: true,
                allowYScaleMin: true,
                allowYScaleMax: true,
                allowLabels: false,
                allowExplodeSlices: false,
                allowDoughnut: false,
                allowGridLines: true,
                defaultShowXAxisLabel: true,
                defaultShowYAxisLabel: true,
                defaultShowXAxis: true,
                defaultShowYAxis: true,
                defaultShowGridLines: true,
                defaultColorScheme: 'natural',
                defaultShowLegend: false,
                defaultShowLabels: false,
                isBar: false,
                isLine: false
            },
        ]
    },
    {
        name: 'Other',
        charts: [
            // {
            //     key: eChartType.BarLineCombo, name: 'Bar/Line Combo Chart',
            //     type: 'bar',
            //     inputFormat: eInputFormat.ComboSeries,
            //     isHorizontal: false,
            //     allowGradient: true,
            //     allowLegend: true,
            //     allowXAxis: true,
            //     allowYAxis: true,
            //     allowXScaleMin: false,
            //     allowXScaleMax: false,
            //     allowYScaleMin: false,
            //     allowYScaleMax: false,
            //     allowLabels: false,
            //     allowExplodeSlices: false,
            //     allowDoughnut: false,
            //     allowGridLines: true,
            //     defaultShowXAxisLabel: true,
            //     defaultShowYAxisLabel: true,
            //     defaultShowXAxis: true,
            //     defaultShowYAxis: true,
            //     defaultShowGridLines: true,
            //     defaultColorScheme: 'natural',
            //     defaultShowLegend: false,
            //     defaultShowLabels: false,
            //     isBar: true
            // },
            // {
            //     key: eChartType.HeatMap, name: 'Heat Map',
            //     inputFormat: eInputFormat.MultiSeries,
            //     isHorizontal: false,
            //     allowGradient: true,
            //     allowLegend: true,
            //     allowXAxis: true,
            //     allowYAxis: true,
            //     allowXScaleMin: true,
            //     allowXScaleMax: true,
            //     allowYScaleMin: false,
            //     allowYScaleMax: false,
            //     allowLabels: false,
            //     allowExplodeSlices: false,
            //     allowDoughnut: false,
            //     allowGridLines: false,
            //     defaultShowXAxisLabel: true,
            //     defaultShowYAxisLabel: false,
            //     defaultShowXAxis: true,
            //     defaultShowYAxis: true,
            //     defaultShowGridLines: true,
            //     defaultColorScheme: 'flame',
            //     defaultShowLegend: true,
            //     isBar: false
            // },
            // {
            //     key: eChartType.TreeMap, name: 'Tree Map',
            //     inputFormat: eInputFormat.SingleSeries,
            //     isHorizontal: false,
            //     allowGradient: true,
            //     allowLegend: false,
            //     allowXAxis: false,
            //     allowYAxis: false,
            //     allowXScaleMin: false,
            //     allowXScaleMax: false,
            //     allowYScaleMin: false,
            //     allowYScaleMax: false,
            //     allowLabels: false,
            //     allowExplodeSlices: false,
            //     allowDoughnut: false,
            //     allowGridLines: true,
            //     defaultShowXAxisLabel: true,
            //     defaultShowYAxisLabel: true,
            //     defaultShowXAxis: true,
            //     defaultShowYAxis: true,
            //     defaultShowGridLines: true,
            //     defaultColorScheme: 'natural',
            //     defaultShowLegend: false,
            //     isBar: false
            // },
            // {
            //     key: eChartType.Cards, name: 'Number Cards',
            //     inputFormat: eInputFormat.SingleSeries,
            //     isHorizontal: false,
            //     allowGradient: false,
            //     allowLegend: false,
            //     allowXAxis: false,
            //     allowYAxis: false,
            //     allowXScaleMin: false,
            //     allowXScaleMax: false,
            //     allowYScaleMin: false,
            //     allowYScaleMax: false,
            //     allowLabels: false,
            //     allowExplodeSlices: false,
            //     allowDoughnut: false,
            //     allowGridLines: false,
            //     defaultShowXAxisLabel: true,
            //     defaultShowYAxisLabel: true,
            //     defaultShowXAxis: true,
            //     defaultShowYAxis: true,
            //     defaultShowGridLines: true,
            //     defaultColorScheme: 'natural',
            //     defaultShowLegend: false,
            //     isBar: false
            // },
            // {
            //     key: eChartType.Gauge, name: 'Gauge',
            //     inputFormat: eInputFormat.SingleSeries,
            //     isHorizontal: false,
            //     allowGradient: false,
            //     allowLegend: true,
            //     allowXAxis: true,
            //     allowYAxis: false,
            //     allowXScaleMin: true,
            //     allowXScaleMax: true,
            //     allowYScaleMin: false,
            //     allowYScaleMax: false,
            //     allowLabels: false,
            //     allowExplodeSlices: false,
            //     allowDoughnut: false,
            //     allowGridLines: false,
            //     defaultShowXAxisLabel: true,
            //     defaultShowYAxisLabel: true,
            //     defaultShowXAxis: true,
            //     defaultShowYAxis: true,
            //     defaultShowGridLines: true,
            //     defaultColorScheme: 'natural',
            //     defaultShowLegend: true,
            //     isBar: false
            // },
            // {
            //     key: eChartType.LinearGauge, name: 'Linear Gauge',
            //     inputFormat: eInputFormat.SingleSeries,
            //     isHorizontal: false,
            //     allowGradient: false,
            //     allowLegend: true,
            //     allowXAxis: true,
            //     allowYAxis: false,
            //     allowXScaleMin: true,
            //     allowXScaleMax: true,
            //     allowYScaleMin: false,
            //     allowYScaleMax: false,
            //     allowLabels: false,
            //     allowExplodeSlices: false,
            //     allowDoughnut: false,
            //     allowGridLines: false,
            //     defaultShowXAxisLabel: true,
            //     defaultShowYAxisLabel: true,
            //     defaultShowXAxis: true,
            //     defaultShowYAxis: true,
            //     defaultShowGridLines: true,
            //     defaultColorScheme: 'natural',
            //     defaultShowLegend: true,
            //     isBar: false
            // },
            // {
            //     key: eChartType.Map, name: 'Google Map',
            //     inputFormat: eInputFormat.GeoCoordinates,
            //     isHorizontal: false,
            //     allowGradient: false,
            //     allowLegend: false,
            //     allowXAxis: false,
            //     allowYAxis: false,
            //     allowXScaleMin: false,
            //     allowXScaleMax: false,
            //     allowYScaleMin: false,
            //     allowYScaleMax: false,
            //     allowLabels: false,
            //     allowExplodeSlices: false,
            //     allowDoughnut: false,
            //     allowGridLines: false,
            //     defaultShowXAxisLabel: false,
            //     defaultShowYAxisLabel: false,
            //     defaultShowXAxis: false,
            //     defaultShowYAxis: false,
            //     defaultShowGridLines: false,
            //     defaultColorScheme: 'natural',
            //     defaultShowLegend: false,
            //     isBar: false,
            //     isLine: false
            // },

        ]
    }
]
